version: '3' 

services:

  
 # letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
 #   container_name: nextcloud-letsencrypt
 #   depends_on:
 #     - proxy
 #   networks:
 #     - nextcloud_network
 #   volumes:
  #    - ./proxy/certs:/etc/nginx/certs:rw
  #    - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
  #    - ./proxy/html:/usr/share/nginx/html:rw
   #   - /etc/localtime:/etc/localtime:ro
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
     # - letsencrypt
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
    #  - VIRTUAL_HOST=nextcloud.YOUR-DOMAIN
    #  - LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
   #   - LETSENCRYPT_EMAIL=YOUR-EMAIL
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
