version: '2'

volumes:
  nextcloud:
  db:
  proxy:

services:
    
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    network:
    - nextcloud-proxy
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
