version: '3.7'

services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
    networks:
      - proxy
    restart: always
    
  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - frontend
  app:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    networks:
      - frontend
    restart: always

networks:
  frontend:
  proxy:
  
volumes:
  nextcloud:
  db-data:
  proxy:
